version: '3.8'

services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n-container
    ports:
      - "5678:5678"
    environment:
      - N8N_SECURE_COOKIE=false
      - N8N_TUNNEL_ENABLED=false
      - WEBHOOK_URL=https://n8n.karyaakhir.web.id/
      - N8N_USER_MANAGEMENT_DISABLED=true
      - N8N_PROTOCOL=https
    volumes:
      - n8n_data:/home/node/.n8n
      - ./monitoring_config:/home/node/.n8n-files/monitoring_config:ro
      - ./logs:/home/node/.n8n-files/logs:ro
      - ./models:/home/node/.n8n-files/models
    networks:
      - mlops_network

  fraud-api:
    build: ./api
    container_name: fraud-api-container
    ports:
      - "5000:5000"
    environment:
      # ✅ Path eksplisit agar tidak ambigu
      - DB_PATH=/app/logs/predictions.db
      - BASELINE_PATH=/app/monitoring_config/static_allbaseline.json
    volumes:
      - ./models:/app/models
      - ./logs:/app/logs
      - ./api:/app
      # ✅ TAMBAHKAN INI — baseline sekarang bisa dibaca fraud-api
      - ./monitoring_config:/app/monitoring_config:ro
    networks:
      - mlops_network

networks:
  mlops_network:
    driver: bridge

volumes:
  n8n_data: