FROM python:3.11-slim

WORKDIR /app

# Install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy source code
COPY . .

# Buat folder untuk mounting volume (Praktik yang sangat baik!)
RUN mkdir -p /app/models
RUN mkdir -p /app/logs

EXPOSE 5000

# Jalankan aplikasi menggunakan Uvicorn (Standar untuk FastAPI)
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "5000"]